/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hk.views;

import com.hk.controllers.PrincipalController;
import com.hk.views.componentes.panel.DefaultPanel;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author pc
 */
public class MenuPrincipal extends javax.swing.JFrame {
    int tipo;
    PrincipalController pcontroller;
    
    
    public MenuPrincipal() {
        initComponents();
    }

    public MenuPrincipal(int tipo) {
        initComponents();
        this.tipo = tipo;
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        pcontroller = new PrincipalController(this);
        pcontroller.setMenuBar(tipo);
        pcontroller.setDefaultPanel();
        //this.contenedorScroll1.setViewportView(new RegistrarEmpleado());
    }
    
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("com/hk/img/logo.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        SideBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        capturarBtn = new javax.swing.JButton();
        contenedor = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal - Sistema de Control de Asistencia");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(1080, 800));

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        SideBar.setBackground(new java.awt.Color(122, 0, 1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hk/img/logo_small.png"))); // NOI18N

        capturarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hk/img/reg_off.png"))); // NOI18N
        capturarBtn.setMnemonic('b');
        capturarBtn.setBorderPainted(false);
        capturarBtn.setContentAreaFilled(false);
        capturarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        capturarBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hk/img/reg.png"))); // NOI18N

        javax.swing.GroupLayout SideBarLayout = new javax.swing.GroupLayout(SideBar);
        SideBar.setLayout(SideBarLayout);
        SideBarLayout.setHorizontalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addContainerGap(71, Short.MAX_VALUE))
            .addComponent(capturarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        SideBarLayout.setVerticalGroup(
            SideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SideBarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(capturarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setBorder(null);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(SideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenedor)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SideBar;
    public javax.swing.JButton capturarBtn;
    public javax.swing.JScrollPane contenedor;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
