/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hk.views;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author HJDS
 */
public class Reentrenamiento extends javax.swing.JFrame {

    /**
     * Creates new form Reentrenamiento
     */
    public Reentrenamiento() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Panel_foto2 = new javax.swing.JPanel();
        recuadro_cam = new javax.swing.JLabel();
        btn_activarYregistrar = new rojerusan.RSButtonMetro();
        counterLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reentrenamiento Empleado");
        setIconImage(getIconImage());
        setResizable(false);

        jPanel2.setMinimumSize(new java.awt.Dimension(350, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(122, 0, 1), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Editar Empleado");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 4, 780, 90));

        Panel_foto2.setBackground(new java.awt.Color(122, 0, 1));
        Panel_foto2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recuadro_cam.setBackground(new java.awt.Color(255, 255, 255));
        recuadro_cam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        Panel_foto2.add(recuadro_cam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 270));

        jPanel3.add(Panel_foto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 320, 290));

        btn_activarYregistrar.setBackground(new java.awt.Color(122, 0, 1));
        btn_activarYregistrar.setText("Activar Cámara y Guardar Datos");
        btn_activarYregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_activarYregistrarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_activarYregistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 320, 40));

        counterLabel1.setBackground(new java.awt.Color(255, 255, 255));
        counterLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        counterLabel1.setForeground(new java.awt.Color(121, 6, 6));
        counterLabel1.setText("00/100");
        counterLabel1.setOpaque(true);
        jPanel3.add(counterLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 50, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 62;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 10);
        jPanel2.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_activarYregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_activarYregistrarActionPerformed
        //startCamera();
    }//GEN-LAST:event_btn_activarYregistrarActionPerformed

   public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("com/hk/img/logo.png"));
        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel_foto2;
    public rojerusan.RSButtonMetro btn_activarYregistrar;
    public javax.swing.JLabel counterLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel recuadro_cam;
    // End of variables declaration//GEN-END:variables
}
